// import Head from "next/head";

// const SEO = ({ pageTitle }) => (
//   <>
//     <Head>
//       <title>{pageTitle && `${pageTitle} - Avya Club`}</title>
//       <meta httpEquiv="x-ua-compatible" content="ie=edge" />
//       <meta name="description" content="Generated by create next app" />
//       <meta name="robots" content="noindex, follow" />
//       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
//       <link rel="icon" href="/favicon.png" />
//     </Head>
//   </>
// );

// export default SEO;

import Head from "next/head";

const SEO = ({
  pageTitle,
  description = "Join Avya Club for premium gym, spa, yoga, zumba, swimming, and club house memberships in Nepal. Book your wellness experience today!",
  keywords = "Avya Club, gym membership Nepal, spa and wellness Kathmandu, yoga classes, zumba classes, swimming pool, club house membership, fitness center",
  ogImage = "/images/og-image.jpg",
  canonical = "https://www.avyaclub.com",
}) => (
  <Head>
    {/* Primary Meta Tags */}
    <title>
      {pageTitle
        ? `${pageTitle} - Avya Club`
        : "Avya Club - Fitness & Wellness in Nepal"}
    </title>
    <meta name="description" content={description} />
    <meta name="keywords" content={keywords} />
    <meta name="robots" content="index, follow" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta httpEquiv="x-ua-compatible" content="ie=edge" />
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />

    {/* Canonical URL */}
    <link rel="canonical" href={canonical} />

    {/* Open Graph Tags */}
    <meta
      property="og:title"
      content={
        pageTitle
          ? `${pageTitle} - Avya Club`
          : "Avya Club - Fitness & Wellness in Nepal"
      }
    />
    <meta property="og:description" content={description} />
    <meta property="og:type" content="website" />
    <meta property="og:url" content={canonical} />
    <meta property="og:image" content={ogImage} />
    <meta property="og:site_name" content="Avya Club" />
    <meta property="og:locale" content="en_US" />

    {/* Twitter Card Tags */}
    <meta name="twitter:card" content="summary_large_image" />
    <meta
      name="twitter:title"
      content={
        pageTitle
          ? `${pageTitle} - Avya Club`
          : "Avya Club - Fitness & Wellness in Nepal"
      }
    />
    <meta name="twitter:description" content={description} />
    <meta name="twitter:image" content={ogImage} />

    {/* JSON-LD Structured Data */}
    <script type="application/ld+json">
      {JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Organization",
        name: "Avya Club",
        url: "https://www.avyaclub.com",
        logo: "/images/logo.png",
        contactPoint: {
          "@type": "ContactPoint",
          telephone: "+977-123-456-7890",
          contactType: "customer service",
          areaServed: "NP",
          availableLanguage: "English",
        },
        sameAs: [
          "https://www.facebook.com/avyaclub",
          "https://www.instagram.com/avyaclub",
          "https://twitter.com/avyaclub",
        ],
        offers: {
          "@type": "OfferCatalog",
          name: "Avya Club Services",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Gym & Functional Fitness",
                description:
                  "Daily, monthly, and yearly gym memberships with professional trainers at Avya Club.",
              },
            },
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Spa & Wellness",
                description:
                  "Relax with Trekkers’ Healing Therapy, Ayurvedic, and Deep Tissue massages at Avya Club.",
              },
            },
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Yoga, Meditation, Zumba, Aerobics",
                description:
                  "Join group classes for yoga, zumba, and aerobics at Avya Club for all fitness levels.",
              },
            },
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Swimming Pool",
                description:
                  "Swimming pool access for adults and kids with daily and monthly options at Avya Club.",
              },
            },
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Club House Membership",
                description:
                  "Exclusive single and couple memberships for Avya Club’s premium facilities.",
              },
            },
          ],
        },
      })}
    </script>
  </Head>
);

export default SEO;
